name: Open Journal Paper
description: Compile and generate Paper metadata
inputs:
  issue_id:
    description: The review issue id for the paper
    required: true
  repository_url:
    description: The repository URL of the submission containing the paper file
    required: true
  branch:
    description: Git branch where the paper is located
    required: false
    default: ""
  journal:
    description: The journal data to use for the paper. Default is 'joss'.
    required: false
    default: joss
  journal_template:
    description: The journal template to compile the paper with. Default is 'joss'.
    required: false
    default: joss
  compile_mode:
    description: Compile a draft PDF or a final accepted paper. Posible values are 'draft' or 'accepted'.
    required: false
    default: draft
outputs:
  pdf_path:
    description: "Path to the generated PDF file"
    value: ${{ steps.compilation-result.outputs.paper_pdf_path }}
  jats_path:
    description: "Path to the generated JATS file"
    value: ${{ steps.compilation-result.outputs.paper_jats_path }}
  crossref_path:
    description: "Path to the generated Crossref XML file"
    value: ${{ steps.compilation-result.outputs.paper_crossref_path }}
  paper_file_path:
    description: "Path to the paper's .md/.tex source file"
    value: ${{ steps.paper-finder.outputs.paper_file_path }}
  paper_title:
    description: "Title of the paper"
    value: ${{ steps.paper-finder.outputs.paper_title }}
runs:
  using: "composite"
  steps:
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.0
        bundler-cache: true
        cache-version: paper-files
        bundler: Gemfile.lock
        working-directory: ${{ github.action_path }}
    - name: Find paper file
      id: paper-finder
      shell: bash
      env:
        ISSUE_ID: ${{ inputs.issue_id }}
        REPO_URL: ${{ inputs.repository_url }}
        PAPER_BRANCH: ${{ inputs.branch }}
        JOURNAL_ALIAS: ${{ inputs.journal }}
        COMPILE_MODE: ${{ inputs.compile_mode }}
        BUNDLE_GEMFILE: ${{ github.action_path }}/Gemfile
      run: |
        bundle exec ruby ${{ github.action_path }}/get_paper.rb
    - name: Build paper artifacts
      id: build-paper
      uses: xuanxu/publishing-artifacts-action@main
      with:
        journal: ${{ inputs.journal_template }}
        paper-path: ${{ steps.paper-finder.outputs.paper_file_path }}
        args: ${{steps.paper-finder.outputs.inara_args}}
    - name: Check results
      id: compilation-result
      shell: bash
      run: |
        ruby ${{ github.action_path }}/check_result.rb ${{ steps.paper-finder.outputs.paper_file_path }} pdf,crossref,jats

branding:
  icon: file-text
  color: blue
